mongo:
    image: mongo:3.0
    hostname: mongo
    ports:
        - "27017:27017"
    volumes:
        - ./mongodata:/data/db
    restart: always
    mem_limit: 1024m

mongoexpress:
    image: mongo-express
    hostname: mongo-express
    links:
        - mongo:mongo
    ports:
        - "8081:8081"
    restart: always
    mem_limit: 128m
    environment:
        - WEB_USER='user'
        - WEB_PASS='pass'
    command: sh -c 'sleep 10 && tini -- node app'
